ViengChuaOnline/ViengChua/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.urls import path, include
from . import views
from .templatetags import temp_tags

urlpatterns = [
    path("", views.MainPageView.as_view(), name="MainPage"),
    path("Login/", views.LoginView.as_view(), name="Login"),
    path("Register/", views.RegisterView.as_view(), name="Register"),
    path("UpdateInfo/", views.UpdateInfoView.as_view(), name="UpdateInfo"),
    path("ChangePassword/", views.ChangePass.as_view(), name="ChangePass"),
    path("DKCN/<str:TheLoaiCau>/", views.DangkyCauNguyen.as_view(), name="DKCN"),
    path("Update/<str:TheLoaiCau>/<int:id>/", views.UpdateCauNguyen.as_view(), name="Update"),
    path("Cung/<str:Phat>/", views.CungPhat.as_view(), name="CungPhat"),
    path("<str:Open>/<str:TheLoai>/", views.List.as_view(), name="List"),
    path("<str:Open>/<str:TheLoai>/<int:ID>/", views.Filter.as_view(), name="Filter"),
    path("<str:Open>/<str:TheLoai>/<str:Ten>/", views.Read.as_view(), name="Read"),
    path("LienHe/", views.LienHe.as_view(), name="LienHe"),
    path("Delete/", temp_tags.delete, name="Delete"),
    path("ChangePassword/", views.ChangePass.as_view(), name="ChangePass"),
    path("Logout", views.logout_view, name="Logout"),
    url(r'^Search/', include('haystack.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ViengChuaOnline/ViengChuaOnline/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ViengChua.urls')),
]

ViengChuaOnline/haystack/urls.py
# encoding: utf-8
from django.conf.urls import url

from haystack.views import SearchView

urlpatterns = [url(r"^$", SearchView(), name="haystack_search")]

ViengChuaOnline/ViengChua/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.functions import ExtractYear
from django.urls import reverse
from django.utils import timezone
from django.utils.timezone import now


class CommonInfo(models.Model):
    HoTen = models.CharField("Họ và Tên", max_length=50)
    NgaySinh = models.DateField("Ngày Sinh", default=timezone.now)
    PhapDanh = models.CharField("Pháp Danh", max_length=50, null=True, blank=True)
    GioiTinh_Choices = (
        ("Nam", "Nam"),
        ("Nữ", "Nữ"),
    )
    GioiTinh = models.CharField("Giới Tính", max_length=3, choices=GioiTinh_Choices)
    DiaChi = models.CharField("Địa Chỉ", max_length=60)
    QueQuan = models.CharField("Quê Quán", max_length=60)
    
    class Meta:
        abstract = True

    def __str__(self):
        return self.HoTen


class MyUser(AbstractUser, CommonInfo):

    class Meta:
        ordering = ("date_joined", "username", )

    def __str__(self):
        return self.username

    def get_fields(self):
        return [(field.verbose_name, field.value_to_string(self)) for field in MyUser._meta.fields]


class InfoCauNguyen(models.Model):
    Image = models.ImageField("Hình Ảnh", upload_to="CauNguyen")
    LoiCauNguyen = models.TextField("Lời Cầu Nguyện")
    ThoiGianCauNguyen = models.DateTimeField("Thời Gian", default=now)
    CommentUser = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    
    class Meta:
        abstract: True


class InfoCauAn(CommonInfo, InfoCauNguyen):

    class Meta:
        ordering = ("-ThoiGianCauNguyen", )

    def get_fields(self):
        return [(field.verbose_name, field.value_to_string(self)) for field in InfoCauAn._meta.fields]

    def get_absolute_url(self):
        return reverse('Filter', kwargs={'Open': "List", 'TheLoai': "CauAn", 'ID': self.id})


class InfoCauSieu(CommonInfo, InfoCauNguyen):
    NgayMat = models.DateField("Ngày Mất")
    HuongDuong = models.PositiveIntegerField("Hưởng Dương")

    class Meta:
        ordering = ("-ThoiGianCauNguyen", )
        
    def get_absolute_url(self):
        return reverse('Filter', kwargs={'Open': "List", 'TheLoai': "CauSieu", 'ID': self.id})

    def save(self, *args, **kwargs):
        self.HuongDuong = ExtractYear(self.NgayMat) - ExtractYear(self.NgaySinh) + 1
        super(InfoCauSieu, self).save(*args, **kwargs)

    def get_fields(self):
        return [(field.verbose_name, field.value_to_string(self)) for field in InfoCauSieu._meta.fields]


class Book(models.Model):
    Name = models.CharField("Tên", max_length=150)
    TacGia = models.CharField("Tác giả", max_length=40)
    Upload = models.FileField(upload_to="Book")
    TheLoai_Choices = (
        ("LichSu", "Lịch sử"),
        ("NghiLe", "Nghi lễ"),
        ("PhatHoc", "Phật học"),
    )
    TheLoai = models.CharField("Thể Loại", max_length=30, choices=TheLoai_Choices)

    class Meta:
        ordering = ("Name", )
        
    def get_absolute_url(self):
        return reverse('Read', kwargs={'Open': "Book", 'TheLoai': self.TheLoai, 'Ten': self.Name})


class VanHoa(models.Model):
    Name = models.CharField("Tên", max_length=150)
    TacGia = models.CharField("Tác giả", max_length=40, null=True)
    Upload = models.FileField(upload_to="VanHoa")
    TheLoai_Choices = (
        ("SongDep", "Sống đẹp"),
        ("NauChay", "Nấu chay"),
        ("AnChay", "Ăn chay"),
    )
    TheLoai = models.CharField("Thể Loại", max_length=30, choices=TheLoai_Choices)

    class Meta:
        ordering = ("Name", )
        
    def get_absolute_url(self):
        return reverse('Read', kwargs={'Open': "VanHoa", 'TheLoai': self.TheLoai, 'Ten': self.Name})


class QuaLuuNiem(models.Model):
    Name = models.CharField("Tên", max_length=200, unique=True)
    Image = models.ImageField("Hình Ảnh", upload_to="Qua")
    Price = models.IntegerField("Giá", null=True)
    Description = models.TextField("Mô tả", max_length=10000, default="Chưa có mô tả")

    class Meta:
        ordering = ("Name", "Price", )

    def get_fields(self):
        return [(field.verbose_name, field.value_to_string(self)) for field in QuaLuuNiem._meta.fields]
    
    def get_absolute_url(self):
        return reverse('Filter', kwargs={'Open': "List", 'TheLoai': "Qua", 'ID': self.id})


class InfoLienHe(models.Model):
    Name = models.CharField(max_length=50)
    Email = models.EmailField(max_length=254)
    Comment = models.TextField("Comment")
    Time = models.DateTimeField("Time", default=now)
    CommentUser = models.ForeignKey(MyUser, on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        ordering = ("Name", "Email", "Time", )

    def __str__(self):
        return self.Name

ViengChuaOnline/ViengChua/forms.py
from django import forms
from django.forms import NumberInput
from django.contrib.auth.forms import UserCreationForm
from django.utils.datetime_safe import date
from .models import MyUser, InfoCauAn, InfoCauSieu, InfoLienHe



class RegisterForm(UserCreationForm):
    class Meta:
        model = MyUser
        fields = ("username", "email", "password1", "password2")


class FullInfoForm(forms.ModelForm):
    class Meta:
        model = MyUser
        fields = ("username", "email", "HoTen", "NgaySinh", "PhapDanh", "GioiTinh", "DiaChi", "QueQuan")
        widgets = {
            "NgaySinh": NumberInput(attrs={"type": "date", "class": "ngay", "id": "ngaysinh"}),
        }

    def __init__(self, *args, **kwargs):
        super(FullInfoForm, self).__init__(*args, **kwargs)
        self.fields["username"].disabled = True
        self.fields["email"].disabled = True

    def clean(self):
        if date.today() < self.cleaned_data["NgaySinh"]:
            raise forms.ValidationError("*Please check the date")
        super(FullInfoForm, self).clean()


class CauAnForm(forms.ModelForm):
    class Meta:
        model = InfoCauAn
        exclude = ("CommentUser", "ThoiGianCauNguyen")
        widgets = {
            "NgaySinh": NumberInput(attrs={"type": "date", "class": "ngay", "id": "ngaysinh"}),
        }

    def form_save(self, form, username):
        self.object = form.save(commit=False)
        user = MyUser.objects.get(username=username)
        self.object.CommentUser = user
        self.object.save()
        
    def clean(self):
        if date.today() < self.cleaned_data["NgaySinh"]:
            raise forms.ValidationError("*Please check the date")
        super(CauAnForm, self).clean()


class CauSieuForm(forms.ModelForm):
    class Meta():
        model = InfoCauSieu
        exclude = ("CommentUser", "ThoiGianCauNguyen")
        widgets = {
            "NgaySinh": NumberInput(attrs={"type": "date", "class": "ngay", "id": "ngaysinh"}),
            "NgayMat": NumberInput(attrs={"type": "date", "class": "ngay", "id": "ngaymat"}),
        }

    def form_save(self, form, username):
        self.object = form.save(commit=False)
        user = MyUser.objects.get(username=username)
        self.object.CommentUser = user
        self.object.save()

    def clean(self):
        if self.cleaned_data["NgayMat"] < self.cleaned_data["NgaySinh"] \
                or date.today() < self.cleaned_data["NgaySinh"]\
                or date.today() < self.cleaned_data["NgayMat"]:
            raise forms.ValidationError("*Please check the date")
        super(CauSieuForm, self).clean()



class LienHeForm(forms.ModelForm):
    class Meta:
        model = InfoLienHe
        exclude = ("CommentUser", "Time", )

    def form_save(self, form, username):
        self.object = form.save(commit=False)
        user = MyUser.objects.get(username=username)
        self.object.CommentUser = user
        self.object.Name = user.username
        self.object.Email = user.email
        self.object.save()

ViengChuaOnline/haystack/forms.py
# encoding: utf-8
from django import forms
from django.utils.encoding import smart_text
from django.utils.text import capfirst
from django.utils.translation import ugettext_lazy as _

from haystack import connections
from haystack.constants import DEFAULT_ALIAS
from haystack.query import EmptySearchQuerySet, SearchQuerySet
from haystack.utils import get_model_ct
from haystack.utils.app_loading import haystack_get_model


def model_choices(using=DEFAULT_ALIAS):
    choices = [
        (get_model_ct(m), capfirst(smart_text(m._meta.verbose_name_plural)))
        for m in connections[using].get_unified_index().get_indexed_models()
    ]
    return sorted(choices, key=lambda x: x[1])


class SearchForm(forms.Form):
    q = forms.CharField(
        required=False,
        label=_("Search"),
        widget=forms.TextInput(attrs={"type": "search"}),
    )

    def __init__(self, *args, **kwargs):
        self.searchqueryset = kwargs.pop("searchqueryset", None)
        self.load_all = kwargs.pop("load_all", False)

        if self.searchqueryset is None:
            self.searchqueryset = SearchQuerySet()

        super(SearchForm, self).__init__(*args, **kwargs)

    def no_query_found(self):
        """
        Determines the behavior when no query was found.

        By default, no results are returned (``EmptySearchQuerySet``).

        Should you want to show all results, override this method in your
        own ``SearchForm`` subclass and do ``return self.searchqueryset.all()``.
        """
        return EmptySearchQuerySet()

    def search(self):
        if not self.is_valid():
            return self.no_query_found()

        if not self.cleaned_data.get("q"):
            return self.no_query_found()
            
        sqs = self.searchqueryset.autocomplete(content_auto1=self.cleaned_data['q'])
        sqs2 = self.searchqueryset.autocomplete(content_auto2=self.cleaned_data['q'])
        sqs3 = self.searchqueryset.autocomplete(content_auto3=self.cleaned_data['q'])
        sqs4 = self.searchqueryset.autocomplete(content_auto4=self.cleaned_data['q'])
        sqs5 = self.searchqueryset.autocomplete(content_auto5=self.cleaned_data['q'])
        sqs6 = self.searchqueryset.autocomplete(content_auto6=self.cleaned_data['q'])
        sqs7 = self.searchqueryset.autocomplete(content_auto7=self.cleaned_data['q'])
        sqs8 = self.searchqueryset.autocomplete(content_auto8=self.cleaned_data['q'])
        sqs9 = self.searchqueryset.autocomplete(content_auto9=self.cleaned_data['q'])
        sqs10 = self.searchqueryset.autocomplete(content_auto10=self.cleaned_data['q'])
        sqs11 = self.searchqueryset.auto_query(self.cleaned_data['q'])
        arr = [sqs2, sqs3, sqs4, sqs5, sqs6, sqs7, sqs8, sqs9, sqs10, sqs11]
        for i in arr:
            if i is None:
                sqs = sqs & i
            else:
                sqs = sqs | i
        
        if self.load_all:
            sqs = sqs.load_all()
        return sqs

    def get_suggestion(self):
        if not self.is_valid():
            return None

        return self.searchqueryset.spelling_suggestion(self.cleaned_data["q"])

class HighlightedSearchForm(SearchForm):
    def search(self):
        return super(HighlightedSearchForm, self).search().highlight()


class FacetedSearchForm(SearchForm):
    def __init__(self, *args, **kwargs):
        self.selected_facets = kwargs.pop("selected_facets", [])
        super(FacetedSearchForm, self).__init__(*args, **kwargs)

    def search(self):
        sqs = super(FacetedSearchForm, self).search()

        # We need to process each facet to ensure that the field name and the
        # value are quoted correctly and separately:
        for facet in self.selected_facets:
            if ":" not in facet:
                continue

            field, value = facet.split(":", 1)

            if value:
                sqs = sqs.narrow('%s:"%s"' % (field, sqs.query.clean(value)))

        return sqs


class ModelSearchForm(SearchForm):
    def __init__(self, *args, **kwargs):
        super(ModelSearchForm, self).__init__(*args, **kwargs)
        self.fields["models"] = forms.MultipleChoiceField(
            choices=model_choices(),
            required=False,
            label=_("Search In"),
            widget=forms.CheckboxSelectMultiple,
        )

    def get_models(self):
        """Return a list of the selected models."""
        search_models = []

        if self.is_valid():
            for model in self.cleaned_data["models"]:
                search_models.append(haystack_get_model(*model.split(".")))

        return search_models

    def search(self):
        sqs = super(ModelSearchForm, self).search()
        return sqs.models(*self.get_models())


class HighlightedModelSearchForm(ModelSearchForm):
    def search(self):
        return super(HighlightedModelSearchForm, self).search().highlight()


class FacetedModelSearchForm(ModelSearchForm):
    selected_facets = forms.CharField(required=False, widget=forms.HiddenInput)

    def search(self):
        sqs = super(FacetedModelSearchForm, self).search()

        if hasattr(self, "cleaned_data") and self.cleaned_data["selected_facets"]:
            sqs = sqs.narrow(self.cleaned_data["selected_facets"])

        return sqs.models(*self.get_models())

ViengChuaOnline/ViengChua/templates/ViengChua/MainPage.html
<!DOCTYPE html>
<html>

<head>
    {% load static %}
    {% load temp_tags %}
    <link rel="stylesheet" href="{% static 'ViengChua/style_1.css' %}">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <meta charset="UTF-8">
    {% block title %}
        <title> Đi Chùa Internet, Chùa Online, Chùa Trực Tuyến | Di Chua Internet, Chua Online, Chua Truc Tuyen</title>
        <link rel="shortcut icon" href="http://tuvien.com/favicon.ico">
    <style>
        @font-face {
            font-family: 'myFirstFont';
            src: url('{% static 'ViengChua/UTM-ThuPhap-ThienAn.ttf' %}');
        }
    </style>
    {% endblock %}
</head>

<body>
<div class="banner">
    <div class = logo>
        <a href="/">
            <img src="{% static 'ViengChua/logo.png' %}" class="logo"/>
        </a>
    </div>
    <div class="navbar">
        <ul>
            <li class="dropdown">
                <a href="" class="dropbtn">Phật</a>
                <div class="dropdown-content">
                    <a href="{% url 'CungPhat' Phat='QuanAmBoTat' %}">Quan Âm Bồ Tát</a>
                    <a href="{% url 'CungPhat' Phat='DiaTangVuong' %}">Địa Tạng Vương Bồ Tát</a>
                </div>
            </li>
            <li class="dropdown">
                <a href="{% url 'Login' %}" class="dropbtn">Đăng Kí</a>
                <div class="dropdown-content">
                    <a href="{% url 'List' Open='List' TheLoai='CauAn' %}">Đăng Kí Cầu An</a>
                    <a href="{% url 'List' Open='List' TheLoai='CauSieu' %}">Đăng Kí Cầu Siêu</a>
                </div>
            </li>
            <li class="dropdown">
                <a href="" class="dropbtn">Tủ Sách</a>
                <div class="dropdown-content">
                    <a href="{% url 'List' Open='Book' TheLoai='LichSu' %}">Lịch Sử Phật Giáo</a>
                    <a href="{% url 'List' Open='Book' TheLoai='NghiLe' %}">Nghi Lễ</a>
                    <a href="{% url 'List' Open='Book' TheLoai='PhatHoc' %}">Phật Học</a>
                </div>
            </li>
            <li class="dropdown">
                <a href="" class="dropbtn">Văn Hóa</a>
                <div class="dropdown-content">
                    <a href="{% url 'List' Open='VanHoa' TheLoai='SongDep' %}">Nghệ Thuật Sống Đẹp</a>
                    <a href="{% url 'List' Open='VanHoa' TheLoai='NauChay' %}">Hướng Dẫn Nấu Chay</a>
                    <a href="{% url 'List' Open='VanHoa' TheLoai='AnChay' %}">Ăn Chay</a>
                </div>
            </li>
            <li class="dropdown"><a href="{% url 'List' Open='List' TheLoai='Qua' %}" class="dropbtn">Quà Lưu Niệm</a></li>
            <li class="dropdown"><a href="{% url 'LienHe' %}" class="dropbtn">Liên Hệ</a></li>
            <li class="dropdown">
                <a href="{% url 'Login' %}" class="dropbtn">{% get_User %}</a>
                <div class="dropdown-content">
                    <a href="{% url 'UpdateInfo' %}">Update Info</a>
                    <a href="{% url 'ChangePass' %}">Đổi mật khẩu</a>
                    <a href="{% url 'Logout' %}">Đăng xuất</a>
                </div>
            </li>
        </ul>
    </div>


    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <div class="searchform">
        <form method="get" action="{% url 'haystack_search' %}" class="autocomplete-me">
            {{ searchform }}
            <br><input type="submit" value="Search" id="search">
        </form>

        <div class="ac-results"></div>
        <script type="text/javascript">
            $("#id_models").wrap("<div class='menu pointerCursor hide'></div>");
            $(".menu.pointerCursor.hide").wrap("<div class='title pointerCursor'>Choose...</div>");
            $(".title.pointerCursor").wrap("<div class='dropdown1'></div>");
            $( "#id_models li" ).wrap( "<div class='option'></div>" );


            function toggleClass(elem,className){
                if (elem.className.indexOf(className) !== -1){
                    elem.className = elem.className.replace(className,'');
                }
                else{
                    elem.className = elem.className.replace(/\s+/g,' ') + 	' ' + className;
                }
                    return elem;
            }

            function toggleDisplay(elem){
                const curDisplayStyle = elem.style.display;
                if (curDisplayStyle === 'none' || curDisplayStyle === ''){
                    elem.style.display = 'block';
                }
                else{
                    elem.style.display = 'none';
                }
            }

            function toggleMenuDisplay(e){
                const dropdown1 = e.currentTarget.parentNode;
                const menu = dropdown1.querySelector('.menu');
                const icon = dropdown1.querySelector('.fa-angle-right');

                toggleClass(menu,'hide');
                toggleClass(icon,'rotate-90');
            }

            //get elements
            const dropdownTitle = document.querySelector('.dropdown1 .title');
            const dropdownOptions = document.querySelectorAll('.dropdown1 .option');

            //bind listeners to these elements
            dropdownTitle.addEventListener('click', toggleMenuDisplay);

            var Autocomplete = function(options) {
                this.form_selector = options.form_selector
                this.url = options.url || '/Search/'
                this.delay = parseInt(options.delay || 300)
                this.minimum_length = parseInt(options.minimum_length || 2)
                this.form_elem = null
                this.query_box = null
            }

            Autocomplete.prototype.setup = function() {
                var self = this

                this.form_elem = $(this.form_selector)
                this.query_box = this.form_elem.find('input[name=q]')

                // Watch the input box.
                this.query_box.on('keyup', function() {
                    var query = self.query_box.val()
                    $('#result').html("")

                if(query.length < self.minimum_length) {
                    return false
                }

                self.fetch(query)
              })

            // On selecting a result, populate the search field.
                this.form_elem.on('click', '.ac-result', function(ev) {
                    self.query_box.val($(this).text())
                    $('.ac-results').html("")
                    $('#result').html("")
                    return false
                })
            }

            Autocomplete.prototype.fetch = function(query) {
                var self = this
                var ajaxData = {
                    'q' : $('#id_q').val(),
                }
                $("#id_models input:checkbox").change(function()
                {
                    if($(this).is(':checked'))
                    {
                        Object.assign(ajaxData, {models: this.value});
                        $.ajax({
                            url: {% url 'haystack_search' %}
                            , data: {
                                'q' : ajaxData.q,
                                'models': ajaxData.models,
                            }
                            , success: function(data) {
                                self.show_results(data);
                            }
                        })
                    }
                    else
                    {
                        $.ajax({
                            url: {% url 'haystack_search' %}
                            , data: {
                                'q' : ajaxData.q,
                            }
                            , success: function(data) {
                                self.show_results(data);
                            }
                        })
                    }
                });
                $.ajax({
                    url: {% url 'haystack_search' %}
                    , data: {
                        'q' : ajaxData.q,
                    }
                    , success: function(data) {
                        self.show_results(data);
                    }
                })
            }

            Autocomplete.prototype.show_results = function(data) {
                // Remove any existing results.
                $('.ac-results').html("")
                var success =  $(data).find('#result');
                $('.ac-results').html(success);
            }

            $(document).ready(function() {
                window.autocomplete = new Autocomplete({
                    form_selector: '.autocomplete-me'
                    })
                window.autocomplete.setup()

                $("label[for='id_models_0']").contents().eq(1).replaceWith(" Sách");
                $("label[for='id_models_1']").contents().eq(1).replaceWith(" Danh Sách Cầu An");
                $("label[for='id_models_2']").contents().eq(1).replaceWith(" Danh Sách Cầu Siêu");
                $("label[for='id_models_3']").contents().eq(1).replaceWith(" Văn Hóa");
            })
        </script>
        <div id="result">
            {% for result in page.object_list %}
                <a href="{{ result.object.get_absolute_url }}">{{ result.object.HoTen }}{{ result.object.Name }}</a>
            {% endfor %}
        </div>
    </div>

    {% block form %}
    {% endblock %}

    {% block image %}
    <script type="text/javascript">
        $(document).ready(function() {
            $(".searchform").css("display","none");
        });
    </script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <a style="margin-top: 1.5%; margin-left: 75%; padding: 5px 10px; text-decoration: none; background:#A08E07; color: white;border-radius: 20%; font-size: 120%; position: absolute" class="Update" href="{% url 'haystack_search' %}"><i class="fa fa-search" aria-hidden="true"> Search</i></a>

    <div class="text">
      <span>Chùa Online TNT</span>
      <div class="text1">Tu Viện Phật Giáo Việt Nam</div>
    </div>
    <div class="PhatImage">
        <img id="phat" src="{% static 'ViengChua/BUDDHA3.gif' %}">
        <img id="phat1" src="{% static 'ViengChua/phat1.png' %}">
        <img id="phat2" src="{% static 'ViengChua/phat1.png' %}">
    </div>
    {% endblock %}

    {% block list %}
    {% endblock %}

    {% block list1 %}
    {% endblock %}

    <iframe src="/media/audio.mp3" allow="autoplay" id="audio" style="display:none"></iframe>
    <audio src="/media/audio.mp3" autoplay loop>
        <source src="/media/audio.mp3" type="audio/mp3">
    </audio>

    <div class="footer">
        <h4>
            <marquee>Xin Quý vị hãy tịnh tâm và chắp tay niệm "Nam Mô A Di Đà Phật" (108 lần) sau khi niệm xong
                xin Qúy vị tụng hồi hướng "Nguyện đem công đức này, Hướng về khắp tất cả, Đệ tử và chúng sanh,
                Đều trọn thành Phật đạo."
            </marquee>
        </h4>
    </div>
</div>
</body>
</html>

ViengChuaOnline/ViengChua/templates/ViengChua/Phat.html
{% extends "ViengChua/MainPage.html" %}

{% block title %}
    <title> Cúng Phật </title>
    <link rel="shortcut icon" href="http://tuvien.com/favicon.ico">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    {% load static %}
    <link rel="stylesheet"  href="{% static 'ViengChua/cung.css' %}">
{% endblock %}


{% block form %}

    <div id="form">
        <img src="{% static 'ViengChua/source.gif' %}" class="logo1">
    </div>
    <br>
    <div id="form1">
        <img src="{% static 'ViengChua/traicay.png' %}" class="traicay">
        <img src="{% static 'ViengChua/heoquay.png' %}" class="heoquay">
    </div>
    <button class="button button2" id="formButton">Cúng</button>
    <button class="button1 button3" id="formButton1">Dâng lễ vật</button>
    <script>
        $('#formButton').on('click', function() {
            if ($('#form').css('opacity') == 0) $('#form').css('opacity', 1);
            else $('#form').css('opacity', 0);
        });
        $('#formButton1').on('click', function() {
            if ($('#form1').css('opacity') == 0) $('#form1').css('opacity', 1);
            else $('#form1').css('opacity', 0);
        });
    </script>
{% endblock %}

{% block image %}
{% endblock %}

ViengChuaOnline/ViengChua/templates/ViengChua/Search.html
{% extends 'ViengChua/MainPage.html' %}

{% block image %}
{% endblock %}